# Generated by Django 4.1.5 on 2023-04-18 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSekreter', '0004_alter_duyuru_duyuru'),
        ('appHasta', '0002_hastarandevu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastarandevu',
            name='hastaSikayet',
        ),
        migrations.RemoveField(
            model_name='hastarandevu',
            name='hastaTC',
        ),
        migrations.RemoveField(
            model_name='hastarandevu',
            name='randevuBrans',
        ),
        migrations.RemoveField(
            model_name='hastarandevu',
            name='randevuDoktor',
        ),
        migrations.RemoveField(
            model_name='hastarandevu',
            name='randevuDurum',
        ),
        migrations.RemoveField(
            model_name='hastarandevu',
            name='randevuSaat',
        ),
        migrations.RemoveField(
            model_name='hastarandevu',
            name='randevuTarih',
        ),
        migrations.AddField(
            model_name='hastarandevu',
            name='randevu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appSekreter.randevubrans', verbose_name='Randevu'),
        ),
    ]
