# Generated by Django 4.1.5 on 2023-04-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHasta', '0004_rename_randevu_hastarandevu_randevuu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hastarandevu',
            old_name='randevuu',
            new_name='randevu',
        ),
    ]
