# Generated by Django 4.1.5 on 2023-04-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSekreter', '0004_alter_duyuru_duyuru'),
        ('appHasta', '0006_hastarandevu_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastarandevu',
            name='randevu',
        ),
        migrations.AddField(
            model_name='hastarandevu',
            name='randevu',
            field=models.ManyToManyField(to='appSekreter.randevubrans', verbose_name=''),
        ),
    ]
