# Generated by Django 4.1.5 on 2023-04-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSekreter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktor',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug Kategori'),
        ),
    ]
